apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ruextmc3y-java-springboot
  janus-idp.io/tekton: ruextmc3y-java-springboot
  backstage.io/kubernetes-id: ruextmc3y-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ruextmc3y-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
